/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IconsFontawesome {
    }
    interface RahaCustomPlayer {
        "videoSrc": string;
    }
}
declare global {
    interface HTMLIconsFontawesomeElement extends Components.IconsFontawesome, HTMLStencilElement {
    }
    var HTMLIconsFontawesomeElement: {
        prototype: HTMLIconsFontawesomeElement;
        new (): HTMLIconsFontawesomeElement;
    };
    interface HTMLRahaCustomPlayerElement extends Components.RahaCustomPlayer, HTMLStencilElement {
    }
    var HTMLRahaCustomPlayerElement: {
        prototype: HTMLRahaCustomPlayerElement;
        new (): HTMLRahaCustomPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "icons-fontawesome": HTMLIconsFontawesomeElement;
        "raha-custom-player": HTMLRahaCustomPlayerElement;
    }
}
declare namespace LocalJSX {
    interface IconsFontawesome {
    }
    interface RahaCustomPlayer {
        "videoSrc"?: string;
    }
    interface IntrinsicElements {
        "icons-fontawesome": IconsFontawesome;
        "raha-custom-player": RahaCustomPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "icons-fontawesome": LocalJSX.IconsFontawesome & JSXBase.HTMLAttributes<HTMLIconsFontawesomeElement>;
            "raha-custom-player": LocalJSX.RahaCustomPlayer & JSXBase.HTMLAttributes<HTMLRahaCustomPlayerElement>;
        }
    }
}
