/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RahaTicketBooking {
        "columns": number;
        "rows": number;
    }
}
declare global {
    interface HTMLRahaTicketBookingElement extends Components.RahaTicketBooking, HTMLStencilElement {
    }
    var HTMLRahaTicketBookingElement: {
        prototype: HTMLRahaTicketBookingElement;
        new (): HTMLRahaTicketBookingElement;
    };
    interface HTMLElementTagNameMap {
        "raha-ticket-booking": HTMLRahaTicketBookingElement;
    }
}
declare namespace LocalJSX {
    interface RahaTicketBooking {
        "columns"?: number;
        "rows"?: number;
    }
    interface IntrinsicElements {
        "raha-ticket-booking": RahaTicketBooking;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "raha-ticket-booking": LocalJSX.RahaTicketBooking & JSXBase.HTMLAttributes<HTMLRahaTicketBookingElement>;
        }
    }
}
