/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RahaLoginForm {
        "emailIsValid": boolean;
        "formTitle": String;
        "mediumPass": boolean;
        "minPassLength": number;
        "minUsernameLength": number;
        "passwordsMatch": boolean;
        "strongPass": boolean;
        "strongPassLegth": number;
        "submitBtn": HTMLElement;
    }
}
declare global {
    interface HTMLRahaLoginFormElement extends Components.RahaLoginForm, HTMLStencilElement {
    }
    var HTMLRahaLoginFormElement: {
        prototype: HTMLRahaLoginFormElement;
        new (): HTMLRahaLoginFormElement;
    };
    interface HTMLElementTagNameMap {
        "raha-login-form": HTMLRahaLoginFormElement;
    }
}
declare namespace LocalJSX {
    interface RahaLoginForm {
        "emailIsValid"?: boolean;
        "formTitle"?: String;
        "mediumPass"?: boolean;
        "minPassLength"?: number;
        "minUsernameLength"?: number;
        "passwordsMatch"?: boolean;
        "strongPass"?: boolean;
        "strongPassLegth"?: number;
        "submitBtn"?: HTMLElement;
    }
    interface IntrinsicElements {
        "raha-login-form": RahaLoginForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "raha-login-form": LocalJSX.RahaLoginForm & JSXBase.HTMLAttributes<HTMLRahaLoginFormElement>;
        }
    }
}
